package com.m3.scalaflavor4j;

import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;

import java.io.File;

import org.junit.Test;

public class BufferedSourceTest {

    @Test
    public void type() throws Exception {
        assertThat(BufferedSource.class, notNullValue());
    }

    @Test
    public void instantiation() throws Exception {
        BufferedSource target = new BufferedSource(new File("input.txt"), null);
        assertThat(target, notNullValue());
    }

    @Test
    public void toByteSeq_A$() throws Exception {
        // TODO auto-generated by JUnit Helper.
        File file = null;
        String enc = null;
        BufferedSource target = new BufferedSource(file, enc);
        Seq<Byte> actual = target.toByteSeq();
        Seq<Byte> expected = null;
        assertThat(actual, is(equalTo(expected)));
    }

    @Test
    public void toCharSeq_A$() throws Exception {
        // TODO auto-generated by JUnit Helper.
        File file = null;
        String enc = null;
        BufferedSource target = new BufferedSource(file, enc);
        Seq<Character> actual = target.toCharSeq();
        Seq<Character> expected = null;
        assertThat(actual, is(equalTo(expected)));
    }

    @Test
    public void getLines_A$() throws Exception {
        // TODO auto-generated by JUnit Helper.
        File file = null;
        String enc = null;
        BufferedSource target = new BufferedSource(file, enc);
        Seq<String> actual = target.getLines();
        Seq<String> expected = null;
        assertThat(actual, is(equalTo(expected)));
    }

}
